//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosClaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Puesto { get; set; }
        public string Email { get; set; }
        public string Cedula { get; set; }
        public System.DateTime FechaContratacion { get; set; }
        public Nullable<int> Cuenta { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
        public virtual Puestos Puestos { get; set; }
    }
}
