//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosClaro
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolCuentas
    {
        public int Id { get; set; }
        public int Cuenta { get; set; }
        public int Rol { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
